replicaCount: 1
image:
  repository: basavabm/myapp
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: nginx
  host: sim.local
  path: /
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  SPRING_PROFILES_ACTIVE: dev
